### ISSUE TITLE
Breadcrumb data is never sent 

### ISSUE THREAD

**Issue by sebj54** [nativescript-community/sentry#5]
### Which platform(s) does your issue occur on?
- iOS & Android 
- iOS/Android versions: see below

### Please, provide the following version numbers that your issue occurs with:

```yaml
OS: macOS 12.0.1
CPU: (4) x64 Intel(R) Core(TM) i3-8100B CPU @ 3.60GHz
Shell: /bin/zsh
node: 14.18.1
npm: 8.1.0
nativescript: 8.1.4

#### android
java: 1.8.0_292
ndk: Not Found
apis: 30
build_tools: 30.0.3
system_images: Not Found

#### ios
xcode: 13.1/13A1030d
cocoapods: 1.10.1
python: 2.7.18
python3: 3.9.6
ruby: 2.7.2
platforms: 
  - DriverKit 21.0.1
  - iOS 15.0
  - macOS 12.0
  - tvOS 15.0
  - watchOS 8.0
```

#### Dependencies

```json
"dependencies": {
  "@nativescript-community/ble": "^3.0.26",
  "@nativescript-community/perms": "^2.2.0",
  "@nativescript-community/sentry": "^3.0.0",
  "@nativescript/core": "^8.0.7",
  "@nativescript/datetimepicker": "^2.1.5",
  "@nativescript/firebase": "^11.1.3",
  "@nativescript/iqkeyboardmanager": "^2.0.0",
  "@nativescript/localize": "^5.0.4",
  "@nativescript/theme": "~3.0.1",
  "@nstudio/nativescript-tracking-transparency": "^1.0.0",
  "@sergeymell/nativescript-svg": "^1.1.1",
  "@triniwiz/nativescript-stripe": "^7.0.0-beta-4",
  "@triniwiz/nativescript-toasty": "^4.1.3",
  "aes-js": "^3.1.2",
  "debounce": "^1.2.1",
  "dotenv": "^10.0.0",
  "js-easing-functions": "^1.0.3",
  "nativescript-exit": "^1.0.1",
  "nativescript-extendedinfo": "^1.0.11",
  "nativescript-ui-gauge": "^8.0.0",
  "nativescript-ui-listview": "~10.0.0",
  "nativescript-vibrate": "^4.0.1",
  "nativescript-vue": "^2.9.0",
  "vuex": "^3.6.2"
},
"devDependencies": {
  "@nativescript/android": "~8.1.1",
  "@nativescript/eslint-plugin": "^0.0.4",
  "@nativescript/ios": "~8.1.0",
  "@nativescript/webpack": "^5.0.0-beta.12",
  "eslint": "^7.27.0",
  "eslint-config-standard": "^16.0.3",
  "eslint-plugin-import": "^2.23.4",
  "eslint-plugin-node": "^11.1.0",
  "eslint-plugin-promise": "^5.1.0",
  "eslint-plugin-vue": "^7.10.0",
  "nativescript-vue-template-compiler": "^2.9.0"
}
```

### Please, tell us how to recreate the issue in as much detail as possible. 

I am trying to log a http breadcrumb (see https://develop.sentry.dev/sdk/event-payloads/breadcrumbs/#breadcrumb-types).

```js
import { addBreadcrumb, Severity } from '@nativescript-community/sentry'

addBreadcrumb({
        type: 'http',
        category: 'xhr',
        level: Severity.Info,
        data: {
            url: 'https://example.com',
            'POST',
            status_code: 200,
            reason: 'OK',
        },
    })
```

When my app restarts, the breadcrumb is sent without data object. I added a console.log here: 

https://github.com/nativescript-community/sentry/blob/4b9cc3dc9453e6a3ef1a18c89c927ef63de2dad2/src/nssentry.android.ts#L505

And `breadcrumb.data` is `undefined` for every breadcrumb when the app restarts. Here is the `breadcrumb` object:

```json
{
  "timestamp": 1637835871.726,
  "type": "http",
  "category": "xhr",
  "level": "info"
}
```

The same thing happens with iOS.

I can investigate more the problem but I don't know what to check. I added a log in Sentry's hub JS file but it does not get called. Do you know what else I can try to fix the problem? Maybe updating Sentry packages?
